#!/bin/bash
code --install-extension aaron-bond.better-comments
code --install-extension bbenoist.vagrant
code --install-extension castwide.solargraph
code --install-extension cazzar09.Gradle
code --install-extension CoenraadS.bracket-pair-colorizer
code --install-extension CraigMaslowski.erb
code --install-extension DavidAnson.vscode-markdownlint
code --install-extension dbaeumer.vscode-eslint
code --install-extension DotJoshJohnson.xml
code --install-extension eamodio.gitlens
code --install-extension EditorConfig.EditorConfig
code --install-extension formulahendry.code-runner
code --install-extension groksrc.ruby
code --install-extension hoovercj.ruby-linter
code --install-extension jcbuisson.vue
code --install-extension jebbs.plantuml
code --install-extension marcostazi.VS-code-vagrantfile
code --install-extension miguel-savignano.ruby-symbols
code --install-extension mikestead.dotenv
code --install-extension misogi.ruby-rubocop
code --install-extension mjmcloug.vscode-elixir
code --install-extension ms-mssql.mssql
code --install-extension ms-python.python
code --install-extension ms-vscode.azure-account
code --install-extension ms-vscode.csharp
code --install-extension ms-vscode.PowerShell
code --install-extension ms-vsts.team
code --install-extension naumovs.color-highlight
code --install-extension nobuhito.printcode
code --install-extension nwolverson.ide-purescript
code --install-extension nwolverson.language-purescript
code --install-extension octref.vetur
code --install-extension oderwat.indent-rainbow
code --install-extension otoniel-isidoro.vscode-ruby-ctags
code --install-extension PeterJausovec.vscode-docker
code --install-extension rebornix.ruby
code --install-extension redhat.java
code --install-extension rust-lang.rust
code --install-extension shaharkazaz.git-merger
code --install-extension Shan.code-settings-sync
code --install-extension stevejpurves.cucumber
code --install-extension timonwong.shellcheck
code --install-extension TravisHaley.pick
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-java-test
code --install-extension vscjava.vscode-maven
code --install-extension vscodevim.vim
code --install-extension maurer.change-case
code --install-extension yzane.markdown-pdf
